vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        outing_file:
            uri_prefix: /uploads/outingImages
            upload_destination: '%kernel.project_dir%/public/uploads/outingImages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
